---
- name: create mds bootstrap directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/ceph/
    - /var/lib/ceph/bootstrap-mds

- name: install pip on debian
  apt:
    name: pip
    state: present
  when: ansible_os_family == 'Debian'

- name: install pip on redhat
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: install six
  pip:
    name: six
    version: 1.9.0

# NOTE (leseb): for version 1.1.0 because https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
