---
- name: install pip on debian
  apt:
    name: pip
    state: present
  when: ansible_os_family == 'Debian'

- name: install epel-release on redhat
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    with_pkg

- name: install pip on redhat
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    with_pkg

- name: install docker on redhat
  yum:
    name: docker-io
    state: present
  when: ansible_os_family == 'RedHat'

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: install six
  pip:
    name: six
    version: 1.9.0
  tags:
    with_pkg

# NOTE (leseb): for version 1.1.0 because https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
  tags:
    with_pkg
